package io.pastework.gradle.dsl;

import org.gradle.api.provider.ListProperty;
import org.gradle.api.provider.Property;

import javax.inject.Inject;
import java.io.Serializable;
import java.util.List;

/**
 * DSL settings to configure component variants generated by this plugin
 * for the consumer to map the environment artifacts to the respective source sets if they have this plugin applied.
 */
public abstract class PublishVariantSettings implements Serializable
{
    @Inject
    public PublishVariantSettings()
    {
        getShouldGenerateVariants().convention(true);
        getGenerateVariantsTo().convention(List.of("java"));
    }

    /**
     * Determine whether the plugin should generate variants
     * <p>
     * By default, this property is set to {@code true}.
     */
    public abstract Property<Boolean> getShouldGenerateVariants();

    /**
     * Determine which components variants should be generated.
     * <p>
     * By default, this property is will target "java" component.
     */
    public abstract ListProperty<String> getGenerateVariantsTo();
}
